import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '../components/layout/Navbar/Navbar';
import ThemeProvider from '@/theme/ThemeProvider';
import NavigationDock from '@/components/layout/NavigationDock/NavigationDock';
import HtmlHeadThemeUpdater from '@/components/common/HtmlHeadThemeUpdater';

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <head>
        {/* Ensure the meta tag is present */}
        <meta name="theme-color" content="black" />
      </head>
      <body className={`${openSans.variable}   antialiased`}>
        <ThemeProvider>
          <HtmlHeadThemeUpdater />
          <Navbar />
          <NavigationDock />
          <div className="mx-24 max-lg:mx-20 max-md:mx-14  max-sm:mx-4 main-content">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
