import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar/Navbar";
import ThemeProvider from "@/theme/ThemeProvider";
import NavigationDock from "@/components/layout/NavigationDock/NavigationDock";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${openSans.variable}   antialiased`}>
        <ThemeProvider>
          <Navbar />
          <NavigationDock />
          <div className="mx-24 max-lg:mx-20 max-md:mx-14  max-sm:mx-4 main-content">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
